/**
 * @fileoverview Check-in service for Foodbank Check-In and Appointment System client application
 * 
 * This module handles all check-in related API operations including
 * initial check-in processing, special requests submission, and
 * appointment scheduling. It provides a clean interface for the
 * client application to interact with the backend check-in system.
 * 
 * @author Lindsey D. Stead
 * @version 1.0.0
 * @since 2025-10-20
 * @license Proprietary - see LICENSE file for details
 * 
 * @see {@link ./api.ts} Base API service
 */

import { api } from './api';

// Check-in data
export interface CheckInData {
  phoneNumber: string;
  lastName: string;
}

// Check-in response data
export interface CheckInResponse {
  success: boolean;
  data?: {
    checkInId: string;
    clientId: string;
    clientName: string;
    appointmentTime?: string;
    phoneNumber: string;
    // Auto-generated next appointment data (available immediately after check-in)
    nextAppointmentDate?: string;
    nextAppointmentTime?: string;
    nextAppointmentISO?: string;
    ticketNumber?: string;
    isAutoGenerated?: boolean;
    appointment?: any;
    client?: any;
  };
  error?: string;
  message?: string;
}

// Complete check-in data
export interface CompleteCheckInData {
  checkInId: string;
  clientId: string;
  clientName: string;
  phoneNumber: string;
  checkInTime: string;
  appointmentTime?: string;
  completionTime: string;
  status: 'Collected';
  
  // Special requests data
  dietaryRestrictions?: string[];
  allergies?: string;
  unwantedFoods?: string;
  additionalInfo?: string;
  householdInfoChanged?: boolean;
  hasMobilityIssues?: boolean;
  diaperSize?: string;
  
  // Appointment details
  notificationPreference?: string;
  email?: string;
  phone?: string;
  phoneCarrier?: string;
  location?: string;
  clientType?: string;
  
  // Next appointment data (auto-generated by admjin system)
  // Note: These fields are no longer used as appointments are auto-generated
}

// Start a check-in
export class CheckInService {
  static async startCheckIn(data: CheckInData): Promise<CheckInResponse> {
    try {
      const response = await api('/checkin', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      });

      const result: CheckInResponse = await response.json();
      return result;
    } catch (error) {
      console.error('Check-in error:', error);
      throw new Error('Failed to start check-in process');
    }
  }

  // Complete a check-in
  static async completeCheckIn(data: CompleteCheckInData): Promise<CheckInResponse> {
    try {
      const response = await api('/checkin/complete', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      });

      const result: CheckInResponse = await response.json();
      return result;
    } catch (error) {
      console.error('Complete check-in error:', error);
      throw new Error('Failed to complete check-in process');
    }
  }
// Get a specific check-in
  static async getCheckIn(checkInId: string): Promise<CheckInResponse> {
    try {
      const response = await api(`/checkin/${checkInId}`);
      const result: CheckInResponse = await response.json();
      return result;
    } catch (error) {
      console.error('Get check-in error:', error);
      throw new Error('Failed to get check-in');
    }
  }

  // Get all check-ins
  static async getAllCheckIns(): Promise<CheckInResponse> {
    try {
      const response = await api('/checkin');
      const result: CheckInResponse = await response.json();
      return result;
    } catch (error) {
      console.error('Get check-ins error:', error);
      throw new Error('Failed to get check-ins');
    }
  }
}
