/**
 * @fileoverview Check-in data grid component for Foodbank Check-In and Appointment System admin panel
 * 
 * This component provides a comprehensive data grid for viewing and
 * managing all check-in data with sorting, filtering, and search
 * capabilities. It handles large datasets efficiently.
 * 
 * @author Lindsey D. Stead
 * @version 1.0.0
 * @since 2025-10-20
 * @license Proprietary - see LICENSE file for details
 * 
 * @see {@link ../DashboardPage.tsx} Dashboard page
 */

import React, { useState, useMemo } from 'react';
import {
  Box,
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  TableContainer,
  Badge,
  HStack,
  VStack,
  Text,
  Icon,
  Button,
  Input,
  Select,
  Flex,
  Card,
  CardHeader,
  CardBody,
  Heading,
  Spinner,
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
  Tooltip,
} from '@chakra-ui/react';
import {
  FiSearch,
  FiRefreshCw,
  FiClock,
  FiMapPin,
  FiUser,
  FiTrendingUp,
  FiTrendingDown,
} from 'react-icons/fi';
interface CheckInRecord {
  id: string;
  timestamp: string;
  clientId: string;
  clientName: string;
  location: string;
  clientType: 'new' | 'returning';
  waitTime: number;
  status: 'Pending' | 'Shipped' | 'Collected' | 'Not Collected' | 'Rescheduled' | 'Cancelled';
  notes?: string;
  nextAppointment?: {
    pickUpDate: string;
    pickUpTime: string;
    isAutoGenerated: boolean;
  };
  volunteerId?: string;
  volunteerName?: string;
  // Additional fields from complete check-in
  dietaryRestrictions?: string[];
  allergies?: string;
  unwantedFoods?: string;
  additionalInfo?: string;
  householdInfoChanged?: boolean;
  hasMobilityIssues?: boolean;
  notificationPreference?: string;
  email?: string;
  phone?: string;
  phoneCarrier?: string;
  completionTime?: string;
  
  // Next appointment data (actual structure)
  nextAppointmentDate?: string;
  nextAppointmentTime?: string;
  nextAppointmentISO?: string;
  ticketNumber?: string;
  isAutoGenerated?: boolean;
  generatedFrom?: string;
  generatedAt?: string;
}

interface CheckInDataTableProps {
  data: CheckInRecord[];
  isLoading?: boolean;
  onRefresh?: () => void;
}

const CheckInDataTable: React.FC<CheckInDataTableProps> = ({
  data,
  isLoading = false,
  onRefresh
}) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [locationFilter, setLocationFilter] = useState<string>('all');
  const [sortField, setSortField] = useState<keyof CheckInRecord>('timestamp');
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('desc');

  const borderColor = 'gray.200'; // Fixed gray border
  const cardBg = 'white'; // Fixed white background

  // Filter and sort data
  const filteredAndSortedData = useMemo(() => {
    let filtered = data.filter(record => {
      const matchesSearch = 
        record.clientName.toLowerCase().includes(searchTerm.toLowerCase()) ||
        record.clientId.toLowerCase().includes(searchTerm.toLowerCase()) ||
        record.volunteerName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        record.notes?.toLowerCase().includes(searchTerm.toLowerCase());

      const matchesStatus = statusFilter === 'all' || record.status === statusFilter;
      const matchesLocation = locationFilter === 'all' || record.location === locationFilter;

      return matchesSearch && matchesStatus && matchesLocation;
    });

    // Sort data
    filtered.sort((a, b) => {
      const aValue = (a as any)[sortField];
      const bValue = (b as any)[sortField];

      if (typeof aValue === 'string' && typeof bValue === 'string') {
        return sortDirection === 'asc' 
          ? aValue.localeCompare(bValue)
          : bValue.localeCompare(aValue);
      }

      if (typeof aValue === 'number' && typeof bValue === 'number') {
        return sortDirection === 'asc' ? aValue - bValue : bValue - aValue;
      }

      return 0;
    });

    return filtered;
  }, [data, searchTerm, statusFilter, locationFilter, sortField, sortDirection]);

  // Get unique locations and statuses for filters
  const uniqueLocations = useMemo(() => {
    const locations = [...new Set(data.map(record => record.location))];
    return locations.sort();
  }, [data]);

  const uniqueStatuses = useMemo(() => {
    const statuses = [...new Set(data.map(record => record.status))];
    return statuses.sort();
  }, [data]);

  // Handle sorting
  const handleSort = (field: keyof CheckInRecord) => {
    if (sortField === field) {
      setSortDirection(sortDirection === 'asc' ? 'desc' : 'asc');
    } else {
      setSortField(field);
      setSortDirection('asc');
    }
  };

  // Get status color
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed': return 'green';
      case 'in-progress': return 'blue';
      case 'waiting': return 'orange';
      default: return 'gray';
    }
  };

  // Get client type color
  const getClientTypeColor = (type: string) => {
    return type === 'new' ? 'green' : 'blue';
  };

  // Format timestamp
  const formatTimestamp = (timestamp: string) => {
    const date = new Date(timestamp);
    return {
      date: date.toLocaleDateString(),
      time: date.toLocaleTimeString(),
      relative: getRelativeTime(date)
    };
  };

  // Get relative time
  const getRelativeTime = (date: Date) => {
    const now = new Date();
    const diffInMinutes = Math.floor((now.getTime() - date.getTime()) / (1000 * 60));
    
    if (diffInMinutes < 1) return 'Just now';
    if (diffInMinutes < 60) return `${diffInMinutes}m ago`;
    if (diffInMinutes < 1440) return `${Math.floor(diffInMinutes / 60)}h ago`;
    return `${Math.floor(diffInMinutes / 1440)}d ago`;
  };


  if (isLoading) {
    return (
      <Card bg={cardBg} border="1px solid" borderColor={borderColor}>
        <CardBody textAlign="center" py={20}>
          <Spinner size="xl" color="brand.500" />
          <Text mt={4} color="gray.600">Loading check-in data...</Text>
        </CardBody>
      </Card>
    );
  }

  if (data.length === 0) {
    return (
      <Card bg={cardBg} border="1px solid" borderColor={borderColor}>
        <CardBody textAlign="center" py={20}>
          <Alert status="info">
            <AlertIcon />
            <AlertTitle>No Data Available</AlertTitle>
            <AlertDescription>No check-in records found for the selected criteria.</AlertDescription>
          </Alert>
        </CardBody>
      </Card>
    );
  }

  return (
    <Card bg={cardBg} border="1px solid" borderColor={borderColor}>
      <CardHeader>
        <Flex justify="space-between" align="center">
          <Heading size="md" color="gray.800">
            <Icon as={FiUser} mr={2} />
            Check-in Records ({filteredAndSortedData.length})
          </Heading>
          <HStack spacing={3}>
            <Button
              size="sm"
              leftIcon={<FiRefreshCw />}
              onClick={onRefresh}
              colorScheme="green"
              variant="outline"
            >
              Refresh
            </Button>
          </HStack>
        </Flex>
      </CardHeader>

      <CardBody>
        {/* Filters */}
        <VStack spacing={4} mb={6} align="stretch">
          <HStack spacing={4} wrap="wrap">
            <Box flex="1" minW="200px">
              <HStack>
                <Icon as={FiSearch} color="gray.500" />
                <Input
                  placeholder="Search clients, volunteers, notes..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  size="sm"
                />
              </HStack>
            </Box>
            
            <Select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              size="sm"
              minW="150px"
            >
              <option value="all">All Statuses</option>
              {uniqueStatuses.map(status => (
                <option key={status} value={status}>
                  {status.charAt(0).toUpperCase() + status.slice(1)}
                </option>
              ))}
            </Select>

            <Select
              value={locationFilter}
              onChange={(e) => setLocationFilter(e.target.value)}
              size="sm"
              minW="150px"
            >
              <option value="all">All Locations</option>
              {uniqueLocations.map(location => (
                <option key={location} value={location}>{location}</option>
              ))}
            </Select>
          </HStack>
        </VStack>

        {/* Data Table */}
        <TableContainer>
          <Table variant="simple" size="sm">
            <Thead>
              <Tr>
                <Th cursor="pointer" onClick={() => handleSort('timestamp')}>
                  <HStack>
                    <Text>Timestamp</Text>
                    {sortField === 'timestamp' && (
                      <Icon 
                        as={sortDirection === 'asc' ? FiTrendingUp : FiTrendingDown} 
                        color="blue.500" 
                        boxSize={3} 
                      />
                    )}
                  </HStack>
                </Th>
                <Th cursor="pointer" onClick={() => handleSort('clientName')}>
                  <HStack>
                    <Text>Client</Text>
                    {sortField === 'clientName' && (
                      <Icon 
                        as={sortDirection === 'asc' ? FiTrendingUp : FiTrendingDown} 
                        color="blue.500" 
                        boxSize={3} 
                      />
                    )}
                  </HStack>
                </Th>
                <Th>Location</Th>
                <Th>Type</Th>
                <Th cursor="pointer" onClick={() => handleSort('waitTime')}>
                  <HStack>
                    <Text>Wait Time</Text>
                    {sortField === 'waitTime' && (
                      <Icon 
                        as={sortDirection === 'asc' ? FiTrendingUp : FiTrendingDown} 
                        color="blue.500" 
                        boxSize={3} 
                      />
                    )}
                  </HStack>
                </Th>
                <Th>Status</Th>
                <Th>Next Appointment</Th>
                <Th>Volunteer</Th>
                <Th>Notes</Th>
              </Tr>
            </Thead>
            <Tbody>
              {filteredAndSortedData.map((record) => {
                const timestamp = formatTimestamp(record.timestamp);
                return (
                  <Tr key={record.id} _hover={{ bg: 'gray.50' }}>
                    <Td>
                      <VStack align="start" spacing={1}>
                        <Text fontSize="sm" fontWeight="500">
                          {timestamp.date}
                        </Text>
                        <Text fontSize="xs" color="gray.500">
                          {timestamp.time}
                        </Text>
                        <Text fontSize="xs" color="blue.500">
                          {timestamp.relative}
                        </Text>
                      </VStack>
                    </Td>
                    <Td>
                      <VStack align="start" spacing={1}>
                        <HStack spacing={2}>
                          <Text fontSize="sm" fontWeight="500">
                            {record.clientName}
                          </Text>
                          {record.hasMobilityIssues && (
                            <Badge colorScheme="red" variant="solid" size="sm">
                              ♿ Mobility
                            </Badge>
                          )}
                        </HStack>
                        <Text fontSize="xs" color="gray.500" fontFamily="mono">
                          {record.clientId}
                        </Text>
                      </VStack>
                    </Td>
                    <Td>
                      <HStack>
                        <Icon as={FiMapPin} color="gray.500" boxSize={3} />
                        <Text fontSize="sm">{record.location}</Text>
                      </HStack>
                    </Td>
                    <Td>
                      <Badge colorScheme={getClientTypeColor(record.clientType)} variant="subtle">
                        {record.clientType === 'new' ? 'New' : 'Returning'}
                      </Badge>
                    </Td>
                    <Td>
                      <HStack>
                        <Icon as={FiClock} color="gray.500" boxSize={3} />
                        <Text fontSize="sm" fontWeight="500">
                          {record.waitTime}m
                        </Text>
                      </HStack>
                    </Td>
                    <Td>
                      <Badge colorScheme={getStatusColor(record.status)} variant="subtle">
                        {record.status.replace('-', ' ')}
                      </Badge>
                    </Td>
                    <Td>
                      {record.nextAppointmentISO ? (
                        <VStack align="start" spacing={1}>
                          <Text fontSize="sm" fontWeight="500">
                            {new Date(record.nextAppointmentISO).toLocaleDateString('en-US', {
                              month: 'short',
                              day: 'numeric',
                              year: 'numeric'
                            })}
                          </Text>
                          <Text fontSize="xs" color="gray.600">
                            {record.nextAppointmentTime || new Date(record.nextAppointmentISO).toLocaleTimeString('en-US', {
                              hour: 'numeric',
                              minute: '2-digit',
                              hour12: true
                            })}
                          </Text>
                          {record.isAutoGenerated && (
                            <Badge size="sm" colorScheme="green" variant="subtle">
                              Auto-scheduled
                            </Badge>
                          )}
                        </VStack>
                      ) : (
                        <Text fontSize="sm" color="gray.400" fontStyle="italic">
                          No next appointment
                        </Text>
                      )}
                    </Td>
                    <Td>
                      {record.volunteerName ? (
                        <Text fontSize="sm" color="gray.700">
                          {record.volunteerName}
                        </Text>
                      ) : (
                        <Text fontSize="sm" color="gray.400" fontStyle="italic">
                          Unassigned
                        </Text>
                      )}
                    </Td>
                    <Td>
                      {record.notes ? (
                        <Tooltip label={record.notes} placement="top">
                          <Text fontSize="sm" color="gray.600" noOfLines={2}>
                            {record.notes}
                          </Text>
                        </Tooltip>
                      ) : (
                        <Text fontSize="sm" color="gray.400" fontStyle="italic">
                          No notes
                        </Text>
                      )}
                    </Td>
                  </Tr>
                );
              })}
            </Tbody>
          </Table>
        </TableContainer>

        {/* Summary */}
        <Box mt={6} p={4} bg="gray.50" borderRadius="md">
          <HStack justify="space-between" fontSize="sm" color="gray.600">
            <Text>
              Showing {filteredAndSortedData.length} of {data.length} records
            </Text>
            <Text>
              Last updated: {new Date().toLocaleTimeString()}
            </Text>
          </HStack>
        </Box>
      </CardBody>
    </Card>
  );
};

export default CheckInDataTable;
